# Generated by Django 4.0.4 on 2022-06-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_profile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experiance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
