# Generated by Django 4.0.4 on 2022-06-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
